version: '3'
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: bookshelf
      MYSQL_ROOT_PASSWORD: bookshelf
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql: ~
